name: moyeo-obs
networks:
  moyeo-net:
    external: true

services:
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: moyeo-redis-exporter
    ports:
      - "${REDIS_EXPORTER_PORT}:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks: [moyeo-net]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: moyeo-kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:${ZOOKEEPER_PORT}
    networks: [moyeo-net]

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: moyeo-kafka-exporter
    ports:
      - "${KAFKA_EXPORTER_PORT}:9308"
    command:
      - "--kafka.server=kafka:${KAFKA_PORT}"
    networks: [moyeo-net]

  prometheus:
    image: prom/prometheus:latest
    container_name: moyeo-prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks: [moyeo-net]

  grafana:
    image: grafana/grafana:latest
    container_name: moyeo-grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks: [moyeo-net]

  loki:
    image: grafana/loki:2.9.8
    container_name: moyeo-loki
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/mnt/config/loki-config.yml
    volumes:
      - ./loki-config.yml:/mnt/config/loki-config.yml
    networks: [moyeo-net]

volumes:
  grafana-data:
  prometheus-data: