global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'moyeo-redis'
    static_configs:
      - targets: ['moyeo-redis-exporter:9121']

  - job_name: 'moyeo-kafka'
    static_configs:
      - targets: ['moyeo-kafka-exporter:9308']

  - job_name: 'moyeo-prometheus'
    static_configs:
      - targets: ['moyeo-prometheus:9090']

  - job_name: 'moyeo-grafana'
    static_configs:
      - targets: ['moyeo-grafana:3000']

  - job_name: 'moyeo-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["moyeo-backend:8080"]