spring:
  application:
    name: moyeo-moyeo-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5000ms
  kafka:
    bootstrap-servers: ${KAFKA_BROKER}
    consumer:
      group-id: challenge-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  web:
    resources:
      add-mappings: false
  messages:
    basename: validation-messages-ko
    encoding: UTF-8
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

jwt:
  secret:
    key: ${JWT_SECRET}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
oauth:
  providers:
    kakao:
      client_id: ${KAKAO_CLIENT_ID}
      redirect_uri: ${KAKAO_REDIRECT_URI}
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
    google:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      redirect_uri: ${GOOGLE_REDIRECT_URI}
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

ai:
  gemini:
    name: GEMINI
    base-url: https://generativelanguage.googleapis.com
    model: gemini-2.5-flash
    key: ${GEMINI_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-components: never