server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}